language: node_js
node_js:
  - "iojs"
  - "7"
notifications:
  email: false
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
  local-dir: dist